name: AWS-CI-CD-pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME : "my-app-python-cicd"
  EB_APPLICATION_NAME       : "My-app"
  EB_ENVIRONMENT_NAME       : "Myapp-env"
  DEPLOY_PACKAGE_NAME       : "python_app${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-east-1"
  AWS_ACCESS_KEY            : ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY            : ${{ secrets.AWS_SECRET_KEY }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3
        
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: copy deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: CI Job Done
        run: echo "CI Job Done"
    

